#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

#ifdef RETPOLINE
MODULE_INFO(retpoline, "Y");
#endif

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x15fe3c83, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xfadf51f7, __VMLINUX_SYMBOL_STR(pnfs_unregister_layoutdriver) },
	{ 0x73e9ceca, __VMLINUX_SYMBOL_STR(nfs4_schedule_session_recovery) },
	{ 0x239fadc1, __VMLINUX_SYMBOL_STR(pnfs_nfs_generic_sync) },
	{ 0x1068c05d, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x9a908b80, __VMLINUX_SYMBOL_STR(test_and_clear_bit) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0x1fdc7df2, __VMLINUX_SYMBOL_STR(_mcount) },
	{ 0xaf5bf6ef, __VMLINUX_SYMBOL_STR(nfs_debug) },
	{ 0xf33847d3, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x2755b825, __VMLINUX_SYMBOL_STR(nfs4_pnfs_ds_connect) },
	{ 0x4d06a3ac, __VMLINUX_SYMBOL_STR(pnfs_generic_clear_request_commit) },
	{ 0xc19322bc, __VMLINUX_SYMBOL_STR(nfs_init_cinfo) },
	{ 0x19f462ab, __VMLINUX_SYMBOL_STR(kfree_call_rcu) },
	{ 0x22384835, __VMLINUX_SYMBOL_STR(nfs_initiate_commit) },
	{ 0x2372ba6d, __VMLINUX_SYMBOL_STR(pnfs_error_mark_layout_for_return) },
	{ 0x29d7279d, __VMLINUX_SYMBOL_STR(nfs4_pnfs_ds_put) },
	{ 0xc267ce41, __VMLINUX_SYMBOL_STR(put_rpccred) },
	{ 0x54bef45, __VMLINUX_SYMBOL_STR(layoutstats_timer) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x61543237, __VMLINUX_SYMBOL_STR(init_user_ns) },
	{ 0x643d9ba1, __VMLINUX_SYMBOL_STR(groups_free) },
	{ 0x70e8af5a, __VMLINUX_SYMBOL_STR(nfs4_mark_deviceid_unavailable) },
	{ 0x1093b108, __VMLINUX_SYMBOL_STR(__tracepoint_nfs4_pnfs_commit_ds) },
	{ 0xa3b6b976, __VMLINUX_SYMBOL_STR(nfs4_decode_mp_ds_addr) },
	{ 0x36856750, __VMLINUX_SYMBOL_STR(nfs_initiate_pgio) },
	{ 0x30f18f2d, __VMLINUX_SYMBOL_STR(nfs4_set_rw_stateid) },
	{ 0xa87cf413, __VMLINUX_SYMBOL_STR(clear_bit) },
	{ 0x7a2af7b4, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0xb9ab1c53, __VMLINUX_SYMBOL_STR(pnfs_generic_commit_pagelist) },
	{ 0xf4c91ed, __VMLINUX_SYMBOL_STR(ns_to_timespec) },
	{ 0x8fff2b9a, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0xd3d2942a, __VMLINUX_SYMBOL_STR(pnfs_generic_recover_commit_reqs) },
	{ 0xe5dc6410, __VMLINUX_SYMBOL_STR(nfs41_setup_sequence) },
	{ 0x5b4b4ed7, __VMLINUX_SYMBOL_STR(nfs4_sequence_done) },
	{ 0x8095b023, __VMLINUX_SYMBOL_STR(xdr_reserve_space) },
	{ 0xe47bdd1c, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_test) },
	{ 0x646e6a8f, __VMLINUX_SYMBOL_STR(nfs4_schedule_lease_recovery) },
	{ 0x6260a2e2, __VMLINUX_SYMBOL_STR(pnfs_update_layout) },
	{ 0x94e7ec90, __VMLINUX_SYMBOL_STR(make_kgid) },
	{ 0xbaf3ba21, __VMLINUX_SYMBOL_STR(rpc_exit) },
	{ 0xfbbc2273, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_cleanup) },
	{ 0x68b31194, __VMLINUX_SYMBOL_STR(pnfs_generic_write_commit_done) },
	{ 0xbaa9ed14, __VMLINUX_SYMBOL_STR(rpc_delay) },
	{ 0xf9c0b663, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0xf31f5004, __VMLINUX_SYMBOL_STR(pnfs_generic_layout_insert_lseg) },
	{ 0xd3259d65, __VMLINUX_SYMBOL_STR(test_and_set_bit) },
	{ 0xb1c8c96c, __VMLINUX_SYMBOL_STR(xdr_init_decode_pages) },
	{ 0xf7141489, __VMLINUX_SYMBOL_STR(from_kuid) },
	{ 0x552bd45b, __VMLINUX_SYMBOL_STR(rpc_call_start) },
	{ 0x985558a1, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x16624d6e, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0x60e3a8b0, __VMLINUX_SYMBOL_STR(nfs40_setup_sequence) },
	{ 0x7428a910, __VMLINUX_SYMBOL_STR(pnfs_read_resend_pnfs) },
	{ 0x20f99045, __VMLINUX_SYMBOL_STR(nfs4_find_get_deviceid) },
	{ 0x237b3544, __VMLINUX_SYMBOL_STR(from_kgid) },
	{ 0xacc6ff74, __VMLINUX_SYMBOL_STR(nfs4_find_or_create_ds_client) },
	{ 0x2e2179f2, __VMLINUX_SYMBOL_STR(rpc_max_payload) },
	{ 0x51c4ae44, __VMLINUX_SYMBOL_STR(nfs_pageio_reset_write_mds) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0x29556eae, __VMLINUX_SYMBOL_STR(pnfs_layout_mark_request_commit) },
	{ 0x1a8229c5, __VMLINUX_SYMBOL_STR(pnfs_destroy_layout) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0xf70e4a4d, __VMLINUX_SYMBOL_STR(preempt_schedule_notrace) },
	{ 0xaa2dcf9d, __VMLINUX_SYMBOL_STR(nfs4_pnfs_ds_add) },
	{ 0x23d33011, __VMLINUX_SYMBOL_STR(pnfs_layoutcommit_inode) },
	{ 0xef655e25, __VMLINUX_SYMBOL_STR(pnfs_put_lseg) },
	{ 0xb9197e70, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0x66f84d74, __VMLINUX_SYMBOL_STR(nfs4_put_deviceid_node) },
	{ 0x4fb32b09, __VMLINUX_SYMBOL_STR(pnfs_report_layoutstat) },
	{ 0xed15fb41, __VMLINUX_SYMBOL_STR(nfs4_print_deviceid) },
	{ 0x638c7ce4, __VMLINUX_SYMBOL_STR(pnfs_set_layoutcommit) },
	{ 0xf0be52ef, __VMLINUX_SYMBOL_STR(pnfs_generic_scan_commit_lists) },
	{ 0x69d3558d, __VMLINUX_SYMBOL_STR(pnfs_generic_rw_release) },
	{ 0x6f7d8599, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x3ec92cb7, __VMLINUX_SYMBOL_STR(make_kuid) },
	{ 0x9a172e7a, __VMLINUX_SYMBOL_STR(nfs4_schedule_stateid_recovery) },
	{ 0x45452cf0, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xe275c38b, __VMLINUX_SYMBOL_STR(nfs4_test_deviceid_unavailable) },
	{ 0x6085edbd, __VMLINUX_SYMBOL_STR(nfs_map_string_to_numeric) },
	{ 0xf999267e, __VMLINUX_SYMBOL_STR(pnfs_generic_commit_release) },
	{ 0x4839bdcf, __VMLINUX_SYMBOL_STR(rpc_sleep_on) },
	{ 0x2bb37d17, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_readpages) },
	{ 0x23d48a92, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x5cd885d5, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x65994f1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque_fixed) },
	{ 0x21dbdd5c, __VMLINUX_SYMBOL_STR(pnfs_read_done_resend_to_mds) },
	{ 0xe5919cb1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque) },
	{ 0xa9b08646, __VMLINUX_SYMBOL_STR(rpc_restart_call_prepare) },
	{ 0xf9699aa0, __VMLINUX_SYMBOL_STR(rpc_wake_up_queued_task) },
	{ 0x3e2b0ba6, __VMLINUX_SYMBOL_STR(groups_alloc) },
	{ 0x802b22e2, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_writepages) },
	{ 0x1916ebea, __VMLINUX_SYMBOL_STR(pnfs_generic_prepare_to_resend_writes) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x4829a47e, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xae8c4d0c, __VMLINUX_SYMBOL_STR(set_bit) },
	{ 0xd0b5b7dc, __VMLINUX_SYMBOL_STR(__tracepoint_nfs4_pnfs_read) },
	{ 0x5a9233, __VMLINUX_SYMBOL_STR(pnfs_write_done_resend_to_mds) },
	{ 0x6ae95b29, __VMLINUX_SYMBOL_STR(rpc_wake_up) },
	{ 0xe138b919, __VMLINUX_SYMBOL_STR(rpc_count_iostats_metrics) },
	{ 0x18b5b1f8, __VMLINUX_SYMBOL_STR(xdr_inline_decode) },
	{ 0xb0480ef3, __VMLINUX_SYMBOL_STR(__tracepoint_nfs4_pnfs_write) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x51720c25, __VMLINUX_SYMBOL_STR(rpc_lookup_generic_cred) },
	{ 0xcf9a3fb7, __VMLINUX_SYMBOL_STR(nfs_pageio_reset_read_mds) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0x18f79a2d, __VMLINUX_SYMBOL_STR(nfs4_init_deviceid_node) },
	{ 0x223fa293, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x9c11e399, __VMLINUX_SYMBOL_STR(nfs_remove_bad_delegation) },
	{ 0x3be448ae, __VMLINUX_SYMBOL_STR(xdr_set_scratch_buffer) },
	{ 0x3200a802, __VMLINUX_SYMBOL_STR(nfs_writeback_update_inode) },
	{ 0x263c3152, __VMLINUX_SYMBOL_STR(bcmp) },
	{ 0x6098d83c, __VMLINUX_SYMBOL_STR(pnfs_register_layoutdriver) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=nfsv4,sunrpc,nfs";

