#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

#ifdef RETPOLINE
MODULE_INFO(retpoline, "Y");
#endif

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x15fe3c83, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x674fc773, __VMLINUX_SYMBOL_STR(vdec_set_no_powerdown) },
	{ 0x6bc3fbc0, __VMLINUX_SYMBOL_STR(__unregister_chrdev) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x452b5e7d, __VMLINUX_SYMBOL_STR(vcodec_profile_read) },
	{ 0x2315967d, __VMLINUX_SYMBOL_STR(cdev_del) },
	{ 0x1f7fb7b9, __VMLINUX_SYMBOL_STR(class_remove_file_ns) },
	{ 0x1068c05d, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xf953d269, __VMLINUX_SYMBOL_STR(cdev_init) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0x1fdc7df2, __VMLINUX_SYMBOL_STR(_mcount) },
	{ 0x220670aa, __VMLINUX_SYMBOL_STR(vdec_release) },
	{ 0x775f27f, __VMLINUX_SYMBOL_STR(vdec_set_pts) },
	{ 0xd6ee688f, __VMLINUX_SYMBOL_STR(vmalloc) },
	{ 0xaf6883c, __VMLINUX_SYMBOL_STR(vdec_set_eos) },
	{ 0xccc1966e, __VMLINUX_SYMBOL_STR(of_find_node_opts_by_path) },
	{ 0x6b4dc2df, __VMLINUX_SYMBOL_STR(vdec_set_video_path) },
	{ 0x97868aef, __VMLINUX_SYMBOL_STR(__kfifo_alloc) },
	{ 0xa6e7d606, __VMLINUX_SYMBOL_STR(of_property_read_u32_index) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0xda3286a2, __VMLINUX_SYMBOL_STR(configs_register_configs) },
	{ 0xb70789e, __VMLINUX_SYMBOL_STR(__might_fault) },
	{ 0x84bc974b, __VMLINUX_SYMBOL_STR(__arch_copy_from_user) },
	{ 0x222ab564, __VMLINUX_SYMBOL_STR(codec_mm_video_tvp_enabled) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x2bbca93f, __VMLINUX_SYMBOL_STR(uio_unregister_device) },
	{ 0x25d8cef2, __VMLINUX_SYMBOL_STR(device_destroy) },
	{ 0x722f7934, __VMLINUX_SYMBOL_STR(__register_chrdev) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x3a4de076, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0xfc51e5a7, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x7485e15e, __VMLINUX_SYMBOL_STR(unregister_chrdev_region) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x556e4390, __VMLINUX_SYMBOL_STR(clk_get_rate) },
	{ 0x774e9131, __VMLINUX_SYMBOL_STR(vdec_input_get_freed_handle) },
	{ 0x7bd5ec57, __VMLINUX_SYMBOL_STR(__platform_driver_register) },
	{ 0x526c3a6c, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x6bcb6e07, __VMLINUX_SYMBOL_STR(__might_sleep) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x159603b9, __VMLINUX_SYMBOL_STR(configs_init_new_node) },
	{ 0x93c3975e, __VMLINUX_SYMBOL_STR(codec_mm_get_free_size) },
	{ 0x285de1a, __VMLINUX_SYMBOL_STR(vdec_poweron) },
	{ 0xab40cca9, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x9e17c4a6, __VMLINUX_SYMBOL_STR(vdec_set_dv_metawithel) },
	{ 0x7c72b17c, __VMLINUX_SYMBOL_STR(jiffies_64) },
	{ 0x3f5c6471, __VMLINUX_SYMBOL_STR(del_timer_sync) },
	{ 0xb1454e54, __VMLINUX_SYMBOL_STR(codec_mm_alloc_for_dma) },
	{ 0xd3259d65, __VMLINUX_SYMBOL_STR(test_and_set_bit) },
	{ 0xdcb764ad, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x4a38b698, __VMLINUX_SYMBOL_STR(cancel_delayed_work) },
	{ 0xa1055f64, __VMLINUX_SYMBOL_STR(codec_mm_dma_flush) },
	{ 0xfb1bac03, __VMLINUX_SYMBOL_STR(device_register) },
	{ 0x97fdbab9, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x7f331e31, __VMLINUX_SYMBOL_STR(codec_reg_write) },
	{ 0xd8fd1768, __VMLINUX_SYMBOL_STR(codec_reg_read) },
	{ 0xadaf6a63, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x985558a1, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xc2ecf989, __VMLINUX_SYMBOL_STR(vdec_reset_userdata_fifo) },
	{ 0xe9e22f03, __VMLINUX_SYMBOL_STR(class_unregister) },
	{ 0x32294ca2, __VMLINUX_SYMBOL_STR(vdec_need_more_data) },
	{ 0x3ffb07ba, __VMLINUX_SYMBOL_STR(vdec_connect) },
	{ 0xfaef0ed, __VMLINUX_SYMBOL_STR(__tasklet_schedule) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x328b7bcb, __VMLINUX_SYMBOL_STR(codec_mm_phys_to_virt) },
	{ 0x906bf319, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x9204e83, __VMLINUX_SYMBOL_STR(vdec_read_user_data) },
	{ 0xab98f378, __VMLINUX_SYMBOL_STR(vdec_status) },
	{ 0xf91c577, __VMLINUX_SYMBOL_STR(is_mult_inc) },
	{ 0x4d553bce, __VMLINUX_SYMBOL_STR(device_create) },
	{ 0x9545af6d, __VMLINUX_SYMBOL_STR(tasklet_init) },
	{ 0xfa5bcf35, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0x85825898, __VMLINUX_SYMBOL_STR(add_timer) },
	{ 0x4c461c1b, __VMLINUX_SYMBOL_STR(dma_release_from_coherent) },
	{ 0x373db350, __VMLINUX_SYMBOL_STR(kstrtoint) },
	{ 0xfa6b132a, __VMLINUX_SYMBOL_STR(vdec_get_vdec_by_id) },
	{ 0x4b297ab8, __VMLINUX_SYMBOL_STR(vdec_get_debug_flags) },
	{ 0x8fd836dd, __VMLINUX_SYMBOL_STR(__class_register) },
	{ 0xe415230d, __VMLINUX_SYMBOL_STR(vdec_poweroff) },
	{ 0x622598b1, __VMLINUX_SYMBOL_STR(init_wait_entry) },
	{ 0x71b6bf77, __VMLINUX_SYMBOL_STR(dma_alloc_from_coherent) },
	{ 0xcffd14db, __VMLINUX_SYMBOL_STR(cdev_add) },
	{ 0x21ec72a7, __VMLINUX_SYMBOL_STR(vdec_input_get_status) },
	{ 0xfe103848, __VMLINUX_SYMBOL_STR(video_fw_reload) },
	{ 0x71fd3b7, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x8f2fb01b, __VMLINUX_SYMBOL_STR(check_efuse_chip) },
	{ 0xdbca38a2, __VMLINUX_SYMBOL_STR(vdec_set_trickmode) },
	{ 0x6fa7af4c, __VMLINUX_SYMBOL_STR(codec_mm_free_for_dma) },
	{ 0x93fca811, __VMLINUX_SYMBOL_STR(__get_free_pages) },
	{ 0xb35dea8f, __VMLINUX_SYMBOL_STR(__arch_copy_to_user) },
	{ 0x9d378f70, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x8bc0c9, __VMLINUX_SYMBOL_STR(get_cpu_major_id) },
	{ 0xd3332ce9, __VMLINUX_SYMBOL_STR(vdec_disconnect) },
	{ 0x8523ef93, __VMLINUX_SYMBOL_STR(codec_mm_get_total_size) },
	{ 0xa6df19bf, __VMLINUX_SYMBOL_STR(vdec_free_irq) },
	{ 0xade6ccca, __VMLINUX_SYMBOL_STR(class_create_file_ns) },
	{ 0xd2a45be2, __VMLINUX_SYMBOL_STR(devm_clk_get) },
	{ 0x23d48a92, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xb93afe0, __VMLINUX_SYMBOL_STR(configs_register_path_configs) },
	{ 0x8e6e149a, __VMLINUX_SYMBOL_STR(dummy_dma_ops) },
	{ 0x96220280, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xdb760f52, __VMLINUX_SYMBOL_STR(__kfifo_free) },
	{ 0x4302d0eb, __VMLINUX_SYMBOL_STR(free_pages) },
	{ 0x65345022, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xcb128141, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x51040f0c, __VMLINUX_SYMBOL_STR(vdec_set_input_buffer) },
	{ 0xf8790d86, __VMLINUX_SYMBOL_STR(vdec_set_isreset) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x4829a47e, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xd62ab15c, __VMLINUX_SYMBOL_STR(vdec_reset) },
	{ 0x2134b32d, __VMLINUX_SYMBOL_STR(vdec_get_qos_info) },
	{ 0xfd446492, __VMLINUX_SYMBOL_STR(vdec_set_format) },
	{ 0x910dd957, __VMLINUX_SYMBOL_STR(class_destroy) },
	{ 0x6073b59a, __VMLINUX_SYMBOL_STR(amports_clock_gate_init) },
	{ 0xc7c4e17d, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0x9c5bc552, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x7d8c8df2, __VMLINUX_SYMBOL_STR(device_unregister) },
	{ 0x8255b784, __VMLINUX_SYMBOL_STR(vdec_request_irq) },
	{ 0xe73225d6, __VMLINUX_SYMBOL_STR(__uio_register_device) },
	{ 0x74780d97, __VMLINUX_SYMBOL_STR(configs_register_path_node) },
	{ 0xfafc5348, __VMLINUX_SYMBOL_STR(vdec_create) },
	{ 0xfc50e75f, __VMLINUX_SYMBOL_STR(vdec_power_reset) },
	{ 0x8c12880d, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0x4119e4af, __VMLINUX_SYMBOL_STR(dev_set_name) },
	{ 0x4128e9e4, __VMLINUX_SYMBOL_STR(vdec_set_pts64) },
	{ 0xb426adda, __VMLINUX_SYMBOL_STR(vdec_init) },
	{ 0x223fa293, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x3e11ced0, __VMLINUX_SYMBOL_STR(__class_create) },
	{ 0xdf1ded2c, __VMLINUX_SYMBOL_STR(amports_switch_gate) },
	{ 0x6c049048, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0x88db9f48, __VMLINUX_SYMBOL_STR(__check_object_size) },
	{ 0x23edd156, __VMLINUX_SYMBOL_STR(vdec_set_decinfo) },
	{ 0x29537c9e, __VMLINUX_SYMBOL_STR(alloc_chrdev_region) },
	{ 0x8bb66f67, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0x4798362e, __VMLINUX_SYMBOL_STR(vdec_set_receive_id) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=decoder_common,firmware,media_clock";

