cmd_drivers/gpu/arm/midgard/mali_kbase_strings.o := clang -Wp,-MD,drivers/gpu/arm/midgard/.mali_kbase_strings.o.d  -nostdinc -isystem /home/jsyou/llvm/build/lib/clang/10.0.0/include -I./arch/arm64/include -I./arch/arm64/include/generated/uapi -I./arch/arm64/include/generated  -I./include -I./arch/arm64/include/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Qunused-arguments -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -Werror -std=gnu89 -fno-PIE --target=aarch64-linux-gnu --prefix=/opt/toolchains/gcc-linaro-6.3.1-2017.02-x86_64_aarch64-linux-gnu/bin//aarch64-linux-gnu- --gcc-toolchain=/opt/toolchains/gcc-linaro-6.3.1-2017.02-x86_64_aarch64-linux-gnu -no-integrated-as -Werror=unknown-warning-option -fno-PIE -mno-implicit-float -DCONFIG_AS_LSE=1 -fno-asynchronous-unwind-tables -fno-pic -Wno-asm-operand-widths -fno-delete-null-pointer-checks -Wno-int-in-bool-context -Wno-address-of-packed-member -O2 -DCC_HAVE_ASM_GOTO -fno-stack-protector -Wno-format-invalid-specifier -Wno-gnu -Wno-tautological-compare -mno-global-merge -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -pg -Wdeclaration-after-statement -Wno-pointer-sign -Wno-array-bounds -fno-strict-overflow -fno-merge-all-constants -fno-stack-check -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Wno-initializer-overrides -Wno-unused-value -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wno-uninitialized -DMALI_CUSTOMER_RELEASE=1 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_MOCK_TEST=0 -DMALI_COVERAGE=0 -DMALI_RELEASE_NAME=\""r12p0-01rel0"\" -DMALI_GCC_WORKAROUND_MIDCOM_4598=0 -DMALI_KBASE_PLATFORM_PATH=../../drivers/gpu/arm/midgard/platform/"devicetree" -I./drivers/staging/android -Idrivers/gpu/arm/midgard -Idrivers/gpu/arm/midgard/platform_dummy -I -Idrivers/gpu/arm/midgard/../../../base -I./include/linux -Idrivers/gpu/arm/midgard/backend/gpu -DMALI_CUSTOMER_RELEASE=1 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_MOCK_TEST=0 -DMALI_COVERAGE=0 -DMALI_RELEASE_NAME=\""r12p0-01rel0"\" -DMALI_GCC_WORKAROUND_MIDCOM_4598=0 -DMALI_KBASE_PLATFORM_PATH=../../drivers/gpu/arm/midgard/platform/"devicetree" -I./drivers/staging/android -Idrivers/gpu/arm/midgard -Idrivers/gpu/arm/midgard/platform_dummy -Idrivers/gpu/arm/midgard/../../../base -I./include/linux -Idrivers/gpu/arm/midgard -Idrivers/gpu/arm/midgard/platform/devicetree -DAMLOGIC_GPU_USE_GPPLL=0 -Idrivers/gpu/arm/midgard/backend/gpu    -DKBUILD_BASENAME='"mali_kbase_strings"'  -DKBUILD_MODNAME='"mali_kbase"' -c -o drivers/gpu/arm/midgard/.tmp_mali_kbase_strings.o drivers/gpu/arm/midgard/mali_kbase_strings.c

source_drivers/gpu/arm/midgard/mali_kbase_strings.o := drivers/gpu/arm/midgard/mali_kbase_strings.c

deps_drivers/gpu/arm/midgard/mali_kbase_strings.o := \
  drivers/gpu/arm/midgard/mali_kbase_strings.h \

drivers/gpu/arm/midgard/mali_kbase_strings.o: $(deps_drivers/gpu/arm/midgard/mali_kbase_strings.o)

$(deps_drivers/gpu/arm/midgard/mali_kbase_strings.o):
